version: '2'
services:
  zookeeper:
    image: confluent/zookeeper:3.4.6-cp1
    expose:
      - 2181

  kafka:
    expose:
      - 9092
      - 8082
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
    image: confluent/kafka:0.10.0.0-cp1
    depends_on:
      - zookeeper

  schema-registry:
    image: confluent/schema-registry:3.0.0
    expose:
      - 2181
    environment:
      - SCHEMA_REGISTRY_KAFKA_STORE_CONNECTION_URL=zookeeper:2181
      - SCHEMA_REGISTRY_DEBUG=true
      - SCHEMA_REGISTRY_KAFKASTORE_TOPIC_REPLICATION_FACTOR=1
    depends_on:
      - kafka
      - zookeeper

  kafka-tools:
    build:
      context: .
      dockerfile: docker/Dockerfile_kafka-tools
    depends_on:
      - zookeeper
      - schema-registry
      - kafka
    environment:
      - BOOTSTRAP_SERVERS=kafka:9092
      - ZOOKEEPER_CONNECT=zookeeper:2181
      - SCHEMA_REGISTRY_URL=http://schema-registry:8081
    working_dir: /usr/src/app
    entrypoint: /bin/bash

  nrepl:
    image: clojure
    depends_on:
      - zookeeper
      - schema-registry
      - kafka
    environment:
      - BOOTSTRAP_SERVERS=kafka:9092
      - ZOOKEEPER_CONNECT=zookeeper:2181
      - SCHEMA_REGISTRY_URL=http://schema-registry:8081
      - PWD=/usr/src/app
    working_dir: ${PWD}
    ports:
      - ${NREPL_PORT}:${NREPL_PORT}
    volumes:
      - .:${PWD}
    entrypoint: >
      lein update-in :dependencies conj \[org.clojure/tools.nrepl\ \"0.2.12\"\] --
           update-in :plugins conj \[refactor-nrepl\ \"2.3.0-SNAPSHOT\"\] --
           update-in :plugins conj \[cider/cider-nrepl\ \"0.14.0-SNAPSHOT\"\] --
           with-profile +test repl :headless :host 0.0.0.0 :port ${NREPL_PORT}
