---
version: 2

jobs:
  build:
    docker:
      - image: quay.io/fundingcircle/clojure:latest
        auth:
          username: $DOCKER_USERNAME
          password: $DOCKER_PASSWORD
    environment:
      _JAVA_OPTIONS: "-Xms1024m -Xmx3072m"
    steps:
      - checkout
      - &restore-cache
        restore_cache:
          keys:
            - libs-cache-{{ checksum "project.clj" }}-{{ checksum ".circleci/config.yml" }}
            - libs-cache-{{ checksum "project.clj" }}
            - libs-cache-
      - run:
          command: nohup confluent start
      - run:
          command: confluent status
      - save_cache:
          key: libs-cache-{{ checksum "project.clj" }}-{{ checksum ".circleci/config.yml" }}
          paths:
            - ~/.m2/
      - run:
          command: lein test

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          context: org-global
